# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RubyConf Colombia
email: organizers@rubyconf.co
description: > # this means to ignore newlines until "baseurl:"
  This will be the second edition of RubyConf Colombia and the conference will
  have even better content, will be bigger in size, will have more talks and will
  be held at a brand new venue. You don’t want to miss it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rubyconf.co" # the base hostname & protocol for your site
twitter_username: rubyconfco
github_username:  rubyconfco

# Build settings
markdown: kramdown

# Index Sections
hero:
  logo: true

collections:
  - speakers
